[config]
schemaVersion = "0.0.1"

[package]
namespace = "danielsitek"
name = "MoreScrapItems"
versionNumber = "0.1.0"
description = "Three scrap items: a QUOTA mug, a framed Sirius portrait, and a Ringhoffer 240 tram."
websiteUrl = "https://github.com/danielsitek/lethal-company-more-scrap-items"
containsNsfwContent = false

[publish]
repository = "https://thunderstore.io"
communities = ["lethal-company"]

[publish.categories]
lethal-company = ["mods", "items", "bepinex"]
